"""
routers/reports.py
------------------
FastAPI router for weekly AI-generated portfolio reports.
Prefix: /api/reports

Reports are generated by Groq AI and stored as JSON blobs in PostgreSQL.
A scheduled job runs every Sunday at 08:00 Bangkok time, but the
POST /generate endpoint allows manual triggering at any time.
"""

import json
import logging
from datetime import datetime, timedelta
from typing import Any

from fastapi import APIRouter, HTTPException

from ai.summarizer import analyze_watchlist_for_weekly
from db.database import db_cursor
from scraper.yahoo import get_stock_info, get_stock_news

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/reports", tags=["Reports"])


def _build_stocks_data() -> list[dict[str, Any]]:
    """
    Assemble the stock performance data needed for weekly analysis.
    Fetches every ticker in the watchlist, retrieves its current info
    and recent news, then packages them for analyze_watchlist_for_weekly.
    """
    try:
        with db_cursor() as cur:
            cur.execute("SELECT ticker FROM watchlist ORDER BY added_at ASC")
            rows = cur.fetchall()

        stocks_data: list[dict[str, Any]] = []
        for row in rows:
            ticker = row["ticker"]
            info = get_stock_info(ticker)
            news = get_stock_news(ticker)
            stocks_data.append(
                {
                    "ticker":       ticker,
                    "price_change": info.get("change_pct", 0.0) or 0.0,
                    "news":         news[:5],
                }
            )
        return stocks_data

    except Exception as exc:
        logger.error("_build_stocks_data() failed: %s", exc)
        return []


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/weekly", summary="Retrieve the latest weekly report")
async def get_weekly_report() -> dict[str, Any]:
    """Return the most recently generated weekly report from PostgreSQL."""
    try:
        with db_cursor() as cur:
            cur.execute(
                """
                SELECT id, week_start, week_end, report_json, created_at
                FROM   weekly_reports
                ORDER  BY created_at DESC
                LIMIT  1
                """
            )
            row = cur.fetchone()

        if not row:
            raise HTTPException(
                status_code=404,
                detail="No weekly report found. Use POST /api/reports/generate to create one.",
            )

        report_data = json.loads(row["report_json"])
        return {
            "id":         row["id"],
            "week_start": row["week_start"],
            "week_end":   row["week_end"],
            "created_at": str(row["created_at"]),
            "report":     report_data,
        }

    except HTTPException:
        raise
    except Exception as exc:
        logger.error("get_weekly_report() failed: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/generate", summary="Manually trigger weekly report generation")
@router.post("/weekly/generate", summary="Generate weekly report (frontend alias)")
async def generate_report() -> dict[str, Any]:
    """Generate a new weekly report immediately and persist it in PostgreSQL."""
    try:
        now = datetime.utcnow()
        week_start = (now - timedelta(days=now.weekday())).strftime("%Y-%m-%d")
        week_end = now.strftime("%Y-%m-%d")

        logger.info("Generating weekly report for %s → %s", week_start, week_end)

        stocks_data = _build_stocks_data()
        report = analyze_watchlist_for_weekly(stocks_data)
        report_json_str = json.dumps(report, ensure_ascii=False)

        with db_cursor() as cur:
            cur.execute(
                """
                INSERT INTO weekly_reports (week_start, week_end, report_json)
                VALUES (%s, %s, %s)
                """,
                (week_start, week_end, report_json_str),
            )

        logger.info("Weekly report saved successfully.")
        return {
            "message":    "Weekly report generated successfully.",
            "week_start": week_start,
            "week_end":   week_end,
            "report":     report,
        }

    except Exception as exc:
        logger.error("generate_report() failed: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))
